apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: guacamole-postgres
  namespace: guacamole
spec:
  instances: 1
  postgresUID: 0
  postgresGID: 0

  managed:
    roles:
      - name: guacamole
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: guacamole
      owner: guacamole
      secret:
        name: guacamole-postgres-secret

  storage:
    size: 4Gi
    storageClass: postgresql
