apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guacamole-ingress
  namespace: guacamole
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: guacamole-add-path@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Web-Based Remote Desktop
    gethomepage.dev/icon: guacamole.png
    gethomepage.dev/name: Guacamole
    gethomepage.dev/href: https://rdp.test.pitlor.dev
spec:
  ingressClassName: traefik
  rules:
  - host: rdp.test.pitlor.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guacamole
            port:
              number: 8080
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-path
  namespace: guacamole
spec:
  addPrefix:
    prefix: /guacamole
  buffering:
    maxRequestBodyBytes: 2000000000
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: guacamole
spec:
  selector:
    app: guacamole
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole
        image: guacamole/guacamole:1.5.5
        env:
        - name: EXTENSIONS
          value: auth-totp
        - name: GUACD_HOSTNAME
          value: guacd
        - name: POSTGRES_DATABASE
          value: guacamole
        - name: POSTGRES_HOSTNAME
          value: guacamole-postgres-rw
        - name: POSTGRES_PASSWORD
          value: guacamole
        - name: POSTGRES_USER
          value: guacamole
        - name: POSTGRESQL_AUTO_CREATE_ACCOUNTS
          value: "true"
        volumeMounts:
        - name: drive
          mountPath: /drive
        startupProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          exec:
            command:
            - "timeout"
            - "1"
            - "bash"
            - "-c"
            - "cat < /dev/null > /dev/tcp/guacamole-postgres-rw/5432"
      volumes:
      - name: drive
        persistentVolumeClaim:
          claimName: guacamole-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-pvc
  namespace: guacamole
spec:
  storageClassName: nas
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
