velero:
  restore: false
  version: 1

google:
  serviceAccountJson: changeme

nas:
  credentialsName: nas-credentials
  ipAddress: 192.168.0.31
  username: docker_containers
  password: changeme

storageClasses:
  - name: nas
    mode: 777
    uid: 1000
    shareName: Homelab
    reclaimPolicy: Delete
    enableProvisioner: true
  - name: nextcloud
    mode: 770
    uid: 33
    shareName: Documents
    reclaimPolicy: Retain
    enableProvisioner: false
  - name: media
    mode: 770
    uid: 1000
    shareName: Media
    reclaimPolicy: Retain
    enableProvisioner: false
  - name: ingest
    mode: 770
    uid: 1000
    shareName: Ingest
    reclaimPolicy: Delete
    enableProvisioner: true

blueskyPds:
  jwtSecret: changeme
  adminPassword: changeme
  plcRotationKey: changeme
  emailSmtpUrl: changeme

infisical:
  encryptionKey: changeme
  authSecret: changeme

postfix:
  server: smtp.gmail.com
  username: changeme
  password: changeme

openArchiver:
  meiliMasterKey: changeme
  jwtSecret: changeme
  encryptionKey: changeme

sunshine:
  password: changeme

externalApplications:
  - name: iMessage
    description: Messaging for iPhone users
    icon: apple.png
    group: Services
    listenToHost: imessage.test.pitlor.dev
    forwardToIp: 192.168.0.165
    forwardToPort: 1234

applications:
  grafana:
    version: 10.1.0
    repository: https://grafana.github.io/helm-charts
    enabled: false
    postgres:
      backupId: "2025-04-08"
  alloy:
    version: 1.3.0
    repository: https://grafana.github.io/helm-charts
    enabled: false
  loki:
    version: 6.42.0
    repository: https://grafana.github.io/helm-charts
    enabled: false
  prometheus:
    version: 27.40.0
    repository: https://prometheus-community.github.io/helm-charts
    enabled: false
  bluesky-pds:
    version: 0.4.0
    repository: https://charts.nerkho.ch
    enabled: true
  infisical-standalone:
    version: 1.7.1
    repository: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    enabled: true
    postgres:
      backupId: "2025-04-08"
  minecraft:
    version: 5.0.0
    repository: https://itzg.github.io/minecraft-server-charts/
    enabled: false
  homepage:
    repository: https://jameswynn.github.io/helm-charts
    version: 2.1.0
    enabled: true
  gitea:
    repository: https://dl.gitea.io/charts
    version: 12.4.0
    enabled: true
    postgres:
      backupId: "2025-04-08"
      postInitApplicationSQLRefs:
        - name: postgres-init
          key: gitea
  vaultwarden:
    version: 0.34.4
    repository: https://guerzon.github.io/vaultwarden
    enabled: true
    postgres:
      backupId: "2025-04-08"
  immich:
    version: 0.10.3
    repository: https://immich-app.github.io/immich-charts
    enabled: true
    postgres:
      imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3
      sharedPreloadLibraries:
        - "vchord.so"
      postInitSQL:
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;
  nextcloud:
    version: 8.4.1
    repository: https://nextcloud.github.io/helm/
    enabled: true
    postgres:
      backupId: "2025-04-08"
  coder:
    version: 2.30.0
    repository: https://helm.coder.com/v2
    enabled: true
    postgres:
      backupId: "2025-04-08"
  authentik:
    version: 2025.12.3
    repository: https://charts.goauthentik.io
    enabled: true
    postgres:
      backupId: "2025-04-08"
  dawarich:
    version: 2.2.3
    repository: https://charts.cogitri.dev
    enabled: true
    postgres:
      backupId: "2025-04-08"
      imageName: ghcr.io/cloudnative-pg/postgis:17-3.6-system-bookworm
      uid: 26
  open-webui:
    version: 12.8.1
    repository: https://helm.openwebui.com/
    enabled: true
    postgres:
      backupId: "2025-04-08"
  homebox:
    version: 0.2.0
    repository: https://bythehugo.github.io/homebox-helm/
    enabled: true
    postgres:
      backupId: "2025-04-08"
  home-assistant:
    version: 0.3.50
    repository: http://pajikos.github.io/home-assistant-helm-chart/
    enabled: true
  actualbudget:
    version: 1.8.7
    repository: https://community-charts.github.io/helm-charts
    enabled: true
  music-assistant-server:
    version: 0.1.9
    repository: http://lmatfy.github.io/charts
    enabled: true
  jellyfin:
    version: 3.0.0
    repository: https://jellyfin.github.io/jellyfin-helm
    enabled: true
  mealie:
    enabled: true
    postgres:
      backupId: "2025-04-08"
  open-archiver:
    enabled: true
    postgres:
      backupId: "2025-04-08"
  guacamole:
    enabled: true
    postgres:
      backupId: "2025-04-08"
      postInitApplicationSQLRefs:
        - name: postgres-init
          key: guacamole
  sunshine:
    enabled: true
  email:
    enabled: true
  octoprint:
    enabled: true
  calibre-web-automated:
    enabled: true