apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-ingress
  namespace: calibre-web-automated
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: eBook management
    gethomepage.dev/icon: calibre.png
    gethomepage.dev/name: Calibre
    gethomepage.dev/group: Apps
    gethomepage.dev/pod-selector: ""
spec:
  ingressClassName: traefik
  rules:
  - host: recipes.test.pitlor.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: calibre-web-automated
            port:
              number: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: calibre-web-automated
  namespace: calibre-web-automated
spec:
  selector:
    app: calibre-web-automated
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web-automated
  namespace: calibre-web-automated
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-web-automated
  template:
    metadata:
      labels:
        app: calibre-web-automated
    spec:
      containers:
        - name: calibre-web-automated
          image: crocodilestick/calibre-web-automated:v4.0.6
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: config
              mountPath: /config
            - name: ingest
              mountPath: /cwa-book-ingest
            - name: library
              mountPath: /calibre-library
            - name: plugins
              mountPath: /config/.config/calibre/plugins
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
        - name: ingest
          persistentVolumeClaim:
            claimName: ingest-pvc
        - name: library
          persistentVolumeClaim:
            claimName: library-pvc
        - name: plugins
          persistentVolumeClaim:
            claimName: plugins-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: calibre-web-automated
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ingest-pvc
  namespace: calibre-web-automated
spec:
  # storageClassName: nas # TODO: move to NAS. I'm getting "mount: permission denied"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library-pvc
  namespace: calibre-web-automated
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # TODO: This needs to be expanded
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugins-pvc
  namespace: calibre-web-automated
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
