{{- range keys .Values.storageClasses.longhorn }}
{{- $storageClass := get $.Values.storageClasses.longhorn . }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ . }}
  annotations:
    "storageclass.kubernetes.io/is-default-class": {{ $storageClass.isDefault | quote }}
  labels:
    "velero.io/exclude-from-backup": {{ not $storageClass.backup | quote }}
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: {{ $storageClass.replicas | quote }}
---
{{ end }}