{{- range keys .Values.storageClasses.nas }}
{{- $storageClass := get $.Values.storageClasses.nas . }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ . }}
  namespace: homelab
provisioner: smb.csi.k8s.io
parameters:
  source: //{{ $.Values.nas.ipAddress }}/{{ $storageClass.shareName }}/
  {{- if $storageClass.enableProvisioner }}
  subDir: "${pvc.metadata.name}"
  csi.storage.k8s.io/provisioner-secret-name: {{ $.Values.nas.credentialsName }}
  csi.storage.k8s.io/provisioner-secret-namespace: homelab
  {{- end }}
  csi.storage.k8s.io/node-stage-secret-name: {{ $.Values.nas.credentialsName }}
  csi.storage.k8s.io/node-stage-secret-namespace: homelab
reclaimPolicy: {{ $storageClass.reclaimPolicy }}
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0{{ $storageClass.mode }}
  - file_mode=0{{ $storageClass.mode }}
  - uid={{ $storageClass.uid }}
  - gid={{ $storageClass.uid }}
---
{{ end }}