apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  capacity:
    storage: 20Gi
  hostPath:
    path: /var/lib/rancher/k3s/storage/ollama
  claimRef:
    name: open--homel-ollama
    namespace: open-webui