apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sunshine-games-ingress
  namespace: sunshine
spec:
  ingressClassName: traefik
  rules:
  - host: games.test.pitlor.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sunshine
            port:
              number: 47989
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sunshine-config-ingress
  namespace: sunshine
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Remote Games
    gethomepage.dev/icon: sunshine.png
    gethomepage.dev/name: Sunshine
    gethomepage.dev/group: Services
    gethomepage.dev/pod-selector: ""
spec:
  ingressClassName: traefik
  rules:
  - host: games-config.test.pitlor.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sunshine
            port:
              number: 47990
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: sunshine
spec:
  insecureSkipVerify: true
---
apiVersion: v1
kind: Service
metadata:
  name: sunshine
  namespace: sunshine
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/service.serverstransport: sunshine-insecure-transport@kubernetescrd
spec:
  selector:
    app: sunshine
  ports:
    {{- range (concat (untilStep 47984 47991 1) (list 48010)) }}
    - protocol: TCP
      name: sunshine-tcp-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
      nodePort: {{ . }}
    {{ end }}
    {{- range (concat (untilStep 47998 48001 1) (list 48010)) }}
    - protocol: UDP
      name: sunshine-udp-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
      nodePort: {{ . }}
    {{- end }}
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sunshine
  namespace: sunshine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sunshine
  template:
    metadata:
      labels:
        app: sunshine
    spec:
      runtimeClassName: nvidia
      containers:
        - name: sunshine
          image: lizardbyte/sunshine:v2026.308.223622-ubuntu-24.04
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/New_York
          volumeMounts:
            - name: sunshine-data
              mountPath: /config
            - name: sunshine-config
              subPath: sunshine.conf
              mountPath: /config/sunshine.conf
            # - name: display-socket
            #   mountPath: /mnt/display-socket
          resources:
            limits:
              nvidia.com/gpu: "1"
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              add:
              - "SYS_ADMIN"
        # - name: vnc-server
        #   image: consol/debian-xfce-vnc:v2.0.4
      volumes:
        - name: sunshine-data
          persistentVolumeClaim:
            claimName: sunshine-pvc
        - name: sunshine-config
          configMap:
            name: sunshine-config
        # - name: display-socket
        #   emptyDir: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunshine-pvc
  namespace: sunshine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
