{{ if index .Values.applications "immich" "enabled" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
  labels:
    "velero.io/exclude-from-backup": "true" # This is already backed up
spec:
  resources:
    requests:
      storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nas
{{ end }}