apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
spec:
  resources:
    requests:
      storage: 10Gi  # TODO can this be lower/dynamic?
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.nasStorageClassName }}