apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
spec:
  resources:
    requests:
      storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nas