apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: homelab
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: jordan@pitlor.dev
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - http01:
        ingress:
          class: traefik