{{ range keys .Values.externalApplications }}
{{ $application := get .Values.externalApplications . }}
{{ include "dev.pitlor.homelab.externalApplications.endpoint-slice" (list $ $application) }}
---
{{ include "dev.pitlor.homelab.externalApplications.service" (list $ $application) }}
---
{{ include "dev.pitlor.homelab.externalApplications.ingress" (list $ $application) }}
{{ end }}