{{- range keys .Values }}
{{- $appName := . -}}
{{- $appConfig := get $.Values . -}}
{{- if $appConfig.enabled -}}
{{ include "dev.pitlor.homelab.applications.namespace" (list $ $appName $appConfig) }}
---
{{ include "dev.pitlor.homelab.applications.helm-chart" (list $ $appName $appConfig) }}
---
{{ include "dev.pitlor.homelab.applications.postgres" (list $ $appName $appConfig) }}
---
{{ end }}
{{ end }}
