apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: pvc-daily-backup
  namespace: homelab
spec:
  schedule: "0 2 * * *"
  template:
    defaultVolumesToFsBackup: true
    includedNamespaces:
      {{- range keys .Values }}
      {{- if (get $.Values .).enabled }}
      - {{ . }}
      {{- end }}
      {{- end }}
    includedResources:
      - persistentvolumeclaims
      - persistentvolumes
    includeClusterResources: true
    storageLocation: gcs-backup-location
    volumeSnapshotLocations:
      - gcs-snapshot-location
    ttl: 720h0m0s