{{ if .Values.velero.restore }}
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: velero-restore-{{ .Values.velero.version }}
  namespace: homelab
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
spec:
  scheduleName: pvc-daily-backup
  restorePVs: true
  includedNamespaces:
    {{- range keys .Values.applications }}
    {{- if (get $.Values.applications .).enabled }}
    - {{ . }}
    {{- end }}
    {{- end }}
{{ end }}