apiVersion: v1
kind: Secret
metadata:
  name: bluesky-secrets
  namespace: bluesky-pds
type: Opaque
data:
  jwtSecret: {{ .Values.blueskyPds.jwtSecret | required "No JWT secret provided" | b64enc | quote }}
  adminPassword: {{ .Values.blueskyPds.adminPassword | required "No admin password provided" | b64enc | quote }}
  plcRotationKey: {{ .Values.blueskyPds.plcRotationKey | required "No PLC rotation key provided" | b64enc | quote }}
  emailSmtpUrl: {{ .Values.blueskyPds.emailSmtpUrl | required "No email SMTP URL provided" | b64enc | quote }}