apiVersion: v1
kind: Secret
metadata:
  name: bluesky-secrets
  namespace: bluesky-pds
stringData:
  jwtSecret: {{ .Values.blueskyPds.jwtSecret | required "No JWT secret provided" | quote }}
  adminPassword: {{ .Values.blueskyPds.adminPassword | required "No admin password provided" | quote }}
  plcRotationKey: {{ .Values.blueskyPds.plcRotationKey | required "No PLC rotation key provided" | quote }}
  # emailSmtpUrl: {{ .Values.blueskyPds.emailSmtpUrl | required "No email SMTP URL provided" | quote }}