{{ if index .Values "bluesky-pds" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: bluesky-secrets
  namespace: bluesky-pds
type: Opaque
data:
  jwtSecret: {{ index .Values "bluesky-pds" "jwtSecret" | required "No JWT secret provided" | b64enc | quote }}
  adminPassword: {{ index .Values "bluesky-pds" "adminPassword" | required "No admin password provided" | b64enc | quote }}
  plcRotationKey: {{ index .Values "bluesky-pds" "plcRotationKey" | required "No PLC rotation key provided" | b64enc | quote }}
  emailSmtpUrl: {{ printf "smtps://send.mail.svc.cluster.local" | b64enc | quote }}
{{ end }}