apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-postgres
  namespace: grafana
spec:
  instances: 1
  postgresUID: 0
  postgresGID: 0

  managed:
    roles:
      - name: grafana
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: grafana
      owner: grafana
      secret:
        name: grafana-postgres-secret

  storage:
    size: 4Gi
    storageClass: nas
