{{- range .Values.applications }}
{{- if .postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .postgres.appName }}-minio-user
  namespace: homelab
type: Opaque
data:
  CONSOLE_ACCESS_KEY: {{ .postgres.appName | b64enc }}
  CONSOLE_SECRET_KEY: {{ .postgres.appName | b64enc }}
{{ end }}
{{ end }}