{{ if index .Values.applications "octoprint" "enabled" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: octoprint-ingress
  namespace: octoprint
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: 3D Printer
    gethomepage.dev/icon: octoprint.png
    gethomepage.dev/name: OctoPrint
    gethomepage.dev/group: Apps
    gethomepage.dev/pod-selector: ""
spec:
  ingressClassName: traefik
  rules:
  - host: 3dprinter.test.pitlor.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: octoprint
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: octoprint
  namespace: octoprint
spec:
  selector:
    app: octoprint
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octoprint
  namespace: octoprint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: octoprint
  template:
    metadata:
      labels:
        app: octoprint
    spec:
      containers:
        - name: octoprint
          image: octoprint/octoprint:1.11.7
          env:
            - name: OCTOPRINT_PORT 
              value: "80"
            # - name: ENABLE_MJPG_STREAMER
            #   value: "true"
          # TODO: Mount USB camera and printer
          volumeMounts:
            - name: config
              mountPath: /octoprint
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  namespace: octoprint
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{ end }}