apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nextcloud-postgres
  namespace: nextcloud
spec:
  instances: 1
  postgresUID: 0
  postgresGID: 0

  managed:
    roles:
      - name: nextcloud
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: nextcloud
      owner: nextcloud
      secret:
        name: nextcloud-postgres-secret

  storage:
    size: 4Gi
    storageClass: postgresql
