{{- range keys .Values.applications }}
{{- $appConfig := get $.Values.applications . -}}
{{- if $appConfig.enabled -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
---
{{ if hasKey $appConfig "repository "}}
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: {{ . | trunc 5 }}-{{ $.Release.Name | trunc 5 }}
  namespace: homelab
spec:
  repo: {{ $appConfig.repository }}
  chart: {{ . }}
  targetNamespace: {{ . }}
  timeout: 10m
  {{- if $.Files.Get (printf "files/values/%s.yaml" .) }}
  valuesContent: |-
{{ tpl ($.Files.Get (printf "files/values/%s.yaml" .)) $ | indent 4 }}
  {{- end }}
{{ end }}
---
{{- if hasKey $appConfig "postgres" -}}
{{- template "dev.pitlor.homelab.postgres" (list $ .) }}
{{- end }}
---
{{ end }}
{{ end }}