{{ range .Values.externalApplications }}
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .name | lower }}-service-endpoints
  labels:
    kubernetes.io/service-name: {{ .name | lower }}-service
    endpointslice.kubernetes.io/managed-by: dev.pitlor
addressType: IPv4
ports:
  - name: http
    appProtocol: http
    protocol: TCP
    port: {{ .forwardToPort }}
endpoints:
  - addresses:
      - {{ .forwardToIp | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name | lower }}-service
  namespace: homelab
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .forwardToPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name | lower }}-ingress
  namespace: homelab
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: homelab-increased-body-limit@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: {{ .description }}
    gethomepage.dev/icon: {{ .icon }}
    gethomepage.dev/name: {{ .name }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .listenToHost }}
      http:
        paths:
          - backend:
              service:
                name: {{ .name | lower }}-service
                port:
                  name: http
            path: /
            pathType: Prefix
---
{{ end }}