apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nas.credentialsName }}
stringData:
  username: {{ .Values.nas.username | quote }}
  password: {{ .Values.nas.password | required "No NAS password provided" | quote }}