apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: upload-ingress
  namespace: upload
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: homelab-increased-body-limit@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: upload.test.pitlor.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: upload
            port:
              number: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: upload
  namespace: upload
spec:
  selector:
    app: upload
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
  namespace: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: uploadserver
        image: python:3.9.22
        command: ["/bin/sh"]
        args: ["-c", "pip install uploadserver; uploadserver"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: upload