origin_web_ui_allowed = wan
bind_address = 0.0.0.0
csrf_allowed_origins = https://games.test.pitlor.dev,https://games-config.test.pitlor.dev,https://192.168.3.25,https://192.168.0.129,https://192.168.0.179
sunshine_name = Pitlor Homelab
capture = nvfbc