{{ if index .Values "home-assistant" "enabled" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-scripts
  namespace: home-assistant
data:
  install_hacs.sh: |-
    cd /config
    [ -f ".HA_VERSION" ]
    ha_not_started=$?

    if [ $ha_not_started -neq 0 ]; then
        touch .HA_VERSION
    fi
    wget -O - https://get.hacs.xyz | bash -
    if [ $ha_not_started -neq 0 ]; then
        rm .HA_VERSION
    fi
{{ end }}