
apiVersion: v1
kind: Service
metadata:
  name: matter
  namespace: home-assistant
spec:
  selector:
    app: matter
  ports:
    - protocol: TCP
      port: 5580
      targetPort: 5580
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matter
  namespace: home-assistant
spec:
  # network mode host???
  replicas: 1
  selector:
    matchLabels:
      app: matter
  template:
    metadata:
      labels:
        app: matter
    spec:
      securityContext:
        appArmorProfile:
          type: Unconfined
      containers:
        - name: mealie
          image: ghcr.io/matter-js/python-matter-server:8.1.2
          volumeMounts:
            - name: mealie-data
              mountPath: /data/
      volumes:
        - name: matter-data
          persistentVolumeClaim:
            claimName: matter-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matter-pvc
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
